#!/bin/bash
#SBATCH -A microbiome
#SBATCH -p cpu
#SBATCH -t 12:00:00
#SBATCH --cpus-per-task=4
#SBATCH --mem=32G
#SBATCH -J dada2_simple_220_160
#SBATCH -o dada2_simple_220_160.out
#SBATCH -e dada2_simple_220_160.err

module load biocontainers
module load qiime2

echo "Starting DADA2 (simple 1) at $(date)"

qiime dada2 denoise-paired \
  --i-demultiplexed-seqs demux2.qza \
  --p-trim-left-f 0 \
  --p-trim-left-r 0 \
  --p-trunc-len-f 220 \
  --p-trunc-len-r 160 \
  --o-table table_simple_220_160.qza \
  --o-representative-sequences rep-seqs_simple_220_160.qza \
  --o-denoising-stats stats_simple_220_160.qza
