#!/bin/bash
#SBATCH -A microbiome
#SBATCH -p cpu
#SBATCH -t 08:00:00
#SBATCH -c 4
#SBATCH --mem=32G
#SBATCH -J qiime_import
#SBATCH -o import2.out
#SBATCH -e import2.err

module load biocontainers
module load qiime2

qiime tools import \
  --type 'SampleData[PairedEndSequencesWithQuality]' \
  --input-path prewean_calf_manifest.txt \
  --input-format PairedEndFastqManifestPhred33V2 \
  --output-path demux2.qza
